"""add prep fields to menu items and served fields to order details

Revision ID: 50588fdfcac1
Revises: 6e8731091086
Create Date: 2026-04-12 18:59:28.782306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50588fdfcac1'
down_revision: Union[str, None] = '6e8731091086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('prep_complexity', sa.String(length=20), nullable=True))
    op.add_column('menu_items', sa.Column('prep_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'prep_minutes')
    op.drop_column('menu_items', 'prep_complexity')
    # ### end Alembic commands ###
