"""add_suppliers_and_supplier_fks

Revision ID: 6e8731091086
Revises: ced2000e7bbc
Create Date: 2026-04-02 22:07:13.857248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8731091086'
down_revision: Union[str, None] = 'ced2000e7bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.add_column('stock_entries', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_entries_supplier_id'), 'stock_entries', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'stock_entries', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.add_column('stock_items', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_stock_items_supplier_id'), 'stock_items', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'stock_items', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_items', type_='foreignkey')
    op.drop_index(op.f('ix_stock_items_supplier_id'), table_name='stock_items')
    op.drop_column('stock_items', 'supplier_id')
    op.drop_constraint(None, 'stock_entries', type_='foreignkey')
    op.drop_index(op.f('ix_stock_entries_supplier_id'), table_name='stock_entries')
    op.drop_column('stock_entries', 'supplier_id')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
